# grafana/provisioning/datasources/datasource.yml
# For all keys see:
# grafana/provisioning/datasources/sample.yaml
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: https://127.0.0.1:9090
    access: proxy
    editable: true
    basicAuth: true
    basicAuthUser: "admin"
    jsonData:
      tlsSkipVerify: true
    secureJsonData:
      basicAuthPassword: "***"

