# Full config documentation: https://prometheus.io/docs/operating/configuration
#
# ca_file must include all intermediate certs, but NOT ending leaf (issued) certificate
# metrics_path defaults to 'http://localhost:9090/metrics'
# scheme defaults to 'http'.

# Global variables
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
                           # How often Prometheus will scrape targets. May be overriden in any target.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
                           # How often evaluate rules to create new time series and to generate alerts.
                           # Keep values of scrape_interval and evaluation_interval the same or prometheus became slow
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'localhost:9093'
      scheme: https
      basic_auth:
        username: service
        password: ***
      tls_config:
        ca_file: /opt/***/intermediate.pem
        server_name: prometeus.***
        insecure_skip_verify: false

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alerts/prometheus-server.yml"
  - "alerts/exporters.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: Template_ConnectToPrometheusService
    basic_auth: &PrometheusServiceBasicAuth
      username: service
      password: ***
    tls_config: &PrometheusServiceTlsConfig
      ca_file: /opt/***/intermediate.pem
      server_name: prometeus.***
      insecure_skip_verify: false

  - job_name: Template_ConnectToPrometheusExporter
    tls_config: &SslAuthClient
      ca_file:   /opt/***/prometheus-ca1.crt
      cert_file: /opt/***/***.crt
      key_file:  /opt/***/***.key
      insecure_skip_verify: false
    relabel_configs : &LabelsDefault
      - source_labels: [__address__]
        regex: '^10.120.[8,9].*'
        target_label: area
        replacement: 'leaseweb'
      - source_labels: [__address__]
        regex: '^10.140.[8,9].*'
        target_label: area
        replacement: 'digitalocean'
      - source_labels: [__address__]
        regex: '^10.160.3[6,7].*'
        target_label: area
        replacement: 'hetzner'
      - source_labels: [__address__]
        regex: '^10.180.[8.9].*'
        target_label: area
        replacement: 'office1'
      - source_labels: [__address__]
        regex: ***:9100
        target_label: __scheme__
        replacement: http

  - job_name: 'pushgateway-local'
    honor_labels: true
    scheme: https
    tls_config: *PrometheusServiceTlsConfig
    basic_auth: *PrometheusServiceBasicAuth
    static_configs:
      - targets: ['localhost:9091']
        labels:
          pushgateway_instance: metricfire

  - job_name: "prometheus-local"
    scrape_interval: 5s
    scheme: https
    tls_config: *PrometheusServiceTlsConfig
    basic_auth: *PrometheusServiceBasicAuth
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'node-exporter-local'
    scrape_interval: 5s
    scheme: https
    tls_config: *PrometheusServiceTlsConfig
    basic_auth: *PrometheusServiceBasicAuth
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'blackbox-local'
    scrape_interval: 5s
    metrics_path: /metrics
    scheme: https
    tls_config: *PrometheusServiceTlsConfig
    basic_auth: *PrometheusServiceBasicAuth
    static_configs:
      - targets: ['localhost:9115']

  - job_name: 'blackbox-http'
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: [http_prometheus]
    scheme: https
    basic_auth: *PrometheusServiceBasicAuth
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prometheus.***:9115
        # replace above with blackbox exporter's real hostname:port.
    file_sd_configs:
      - files:
        - targets/http.yml

  - job_name: 'blackbox-tcp'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    scrape_interval: 10s
    file_sd_configs:
      - files:
        - targets/ssl.yml

  - job_name: 'blackbox-icmp'
    metrics_path: /probe
    params:
      module: [icmp]
    scheme: https
    basic_auth: *PrometheusServiceBasicAuth
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prometheus.***:9115
        # replace above with blackbox exporter's real hostname:port.
      - source_labels: [__address__]
        regex: '^10.120.[8,9].*'
        target_label: area
        replacement: 'leaseweb'
      - source_labels: [__address__]
        regex: '^10.140.[8,9].*'
        target_label: area
        replacement: 'digitalocean'
      - source_labels: [__address__]
        regex: '^10.160.3[6,7].*'
        target_label: area
        replacement: 'hetzner'
      - source_labels: [__address__]
        regex: '^10.180.[8,9].*'
        target_label: area
        replacement: 'office1'
    file_sd_configs:
      - files:
        - targets/icmp.yml

  - job_name: 'mysql-exporter'
    relabel_configs: *LabelsDefault
    scheme: https
    tls_config: *SslAuthClient
    file_sd_configs:
      - files:
        - targets/mysql.yml

  - job_name: 'windows-exporter'
    relabel_configs: *LabelsDefault
    scheme: https
    tls_config: *SslAuthClient
    file_sd_configs:
      - files:
        - targets/windows.yml

  - job_name: 'gitlab-exporter'
    relabel_configs: *LabelsDefault
    metrics_path: /-/metrics
    scheme: https
    file_sd_configs:
      - files:
        - targets/gitlab.yml

  - job_name: 'node-exporter'
    scrape_interval: 5m
    scrape_timeout: 2m
    scheme: https
    tls_config: *SslAuthClient
    file_sd_configs:
      - files:
        - targets/linux.yml
    relabel_configs : &LabelsDefault
      - source_labels: [__address__]
        regex: '^10.120.[8,9].*'
        target_label: area
        replacement: 'leaseweb'
      - source_labels: [__address__]
        regex: '^10.140.[8,9].*'
        target_label: area
        replacement: 'digitalocean'
      - source_labels: [__address__]
        regex: '^10.160.3[6,7].*'
        target_label: area
        replacement: 'hetzner'
      - source_labels: [__address__]
        regex: '^10.180.[8,9].*'
        target_label: area
        replacement: 'office1'
